server:
  port: 8000
  servlet:
    context-path: /bgms


### resource
spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
    servlet:
      load-on-startup: 0
  #    freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    spring.freemarker.settings.number_format: 0.##########
#  mail:
#    host: smtp.163.com
#    port: 25
#    username:
#    password:
#    properties:
#    default-encoding: utf-8
#    test-connection: true
logging:
  config: classpath:logback-spring.xml
  level:
    dao: error
    org:
      mybatis: error
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
