server:
  port: 8000
  servlet:
    context-path: /bgms


### resource
spring:
  profiles:
    active: dev
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
    servlet:
      load-on-startup: 0
  #    freemarker
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    spring.freemarker.settings.number_format: 0.##########
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
